spring:
  application:
    name: User-Service
security:
  oauth2:
    client:
      registration:
        userserviceclient:
          client-id:
          client-secret:
          scope: user_info
          redirect-uri:
          client-authentication-method: basic
          authorization-grant-type: authorization_code
          provider: user-service-provider
        provider:
          user-service-provider:
            token-uri:
            authorization-uri:
            user-info-uri:
            user-name-attribute: username




      client-id:
      client-secret:
    resource:
      token-info-uri: http://localhost:8080/auth/oauth/check_token
      #user-info-uri: http://localhost:1234/auth/oauth/user
      jwt:
        key-uri: http://localhost:8080/auth/oauth/token_key
server:
  port: 8089